// leave off @2x/@3x
const images = {
  logo: require('../Images/ir.png'),
  clearLogo: require('../Images/top_logo.png'),
  launch: require('../Images/launch-icon.png'),
  ready: require('../Images/your-app.png'),
  ignite: require('../Images/ignite_logo.png'),
  igniteClear: require('../Images/ignite-logo-transparent.png'),
  tileBg: require('../Images/tile_bg.png'),
  background: require('../Images/BG.png'),
  buttonBackground: require('../Images/button-bg.png'),
  api: require('../Images/Icons/icon-api-testing.png'),
  components: require('../Images/Icons/icon-components.png'),
  deviceInfo: require('../Images/Icons/icon-device-information.png'),
  faq: require('../Images/Icons/faq-icon.png'),
  home: require('../Images/Icons/icon-home.png'),
  theme: require('../Images/Icons/icon-theme.png'),
  usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  chevronRight: require('../Images/Icons/chevron-right.png'),
  hamburger: require('../Images/Icons/hamburger.png'),
  backButton: require('../Images/Icons/back-button.png'),
  closeButton: require('../Images/Icons/close-button.png'),
  tokoemas: require('../Images/tokoemas.png'),
  gold: require('../Images/gold.png'),
  pantes: require('../Images/pantes.jpg'),
  emptyTrans: require('../Images/empty-transactions.png'),
  DefaultAvatar: require('../Images/DefaultAvatar.png'),
  iconHistory: require('../Images/icon-medical-history.png'),
  FlashOff: require('../Images/FlashOff.png'),
  FlashOn: require('../Images/FlashOn.png'),
  IconCancel: require('../Images/IconCancel.png'),
  cameraClick: require('../Images/cameraClick.png'),
  CameraSwitch: require('../Images/CameraSwitch.png'),
  camera: require('../Images/camera.png'),
}

export default images
